[package]
name = "recuerdame-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2", features = ["full", "parsing"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
recuerdame = { path = "../recuerdame" }


[lib]
proc-macro = true
